// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dphcbbxrpdpdzsrsdkgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwaGNiYnhycGRwZHpzcnNka2dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Nzg2OTksImV4cCI6MjA3MjM1NDY5OX0.XLOUMMb-6uBWZWjRAGeCxIrLbQi_X40W1jkZJDKb8y8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});