// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nldlmkdwlogpocdbhujl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sZGxta2R3bG9ncG9jZGJodWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NzgzMzcsImV4cCI6MjA3MjM1NDMzN30.zatP8JT2a71w_1BNjJD5nuqbDGg2ad5uBSUcu0dE7c4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});